#!/bin/tcsh

#BSUB -q santiso
#BSUB -n 12
#BSUB -W 24:00
#BSUB -J gmx_testing
#BSUB -o o.%J
#BSUB -e e.%J

module load PrgEnv-intel
module load /rs1/researchers/e/eesantis/jpmckibb/modulefiles/plumed/

mpirun -np 4 plumed driver --mf_xtc traj.xtc --plumed plumed.dat
